const { PORT = 3001, MONGO_DB = 'mongodb://127.0.0.1:27017/mestodb' } = process.env;
const ERROR_BAD_REQUEST = 400;
const ERROR_AUTH = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_NOUNIQUE = 409;
const ERROR_DEFAULT = 500;

module.exports = {
  ERROR_BAD_REQUEST,
  ERROR_AUTH,
  ERROR_FORBIDDEN,
  ERROR_NOT_FOUND,
  ERROR_NOUNIQUE,
  ERROR_DEFAULT,
  PORT,
  MONGO_DB,
};
